const fs = require('fs');
const path = require('path');
bgmList = fs.readdirSync('public/audios')
    .filter(file => file.endsWith('.mp3') || file.endsWith('.wav') || file.endsWith('.flac'))
    // .map(file => file.replace('\\','/'))
    .map(file => path.join('/audios/', file));
pictureList = fs.readdirSync('public/pics')
    .filter(file => file.endsWith('.jpg') || file.endsWith('.png') || file.endsWith('.jpeg') || file.endsWith('.webp'))
    // .map(file => file.replace('\\','/'))
    .map(file => path.join('/pics/', file));
module.exports = {bgmList,pictureList};